version: '3.7'

networks:
  chuose_network:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: chuose_backend
    ports:
      - '4000:4000'
    networks:
      - chuose_network
  frontend:
    build: ./frontend
    container_name: chuose_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - chuose_network
